const TeamDetails = [
  {
    name: "Camisha Shiny V",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Camisha_Shiny_21h206.png",
  },
  {
    name: "Keshnee N",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Keshnee_21c111.png",
  },
  {
    name: "Lindsey R Macedo",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Lindsey.png",
  },
  {
    name: "Abina Sree",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Abina_Sree_21d203.png",
  },
  {
    name: "Abinaya S",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Abinaya_S_22N202.png",
  },
  {
    name: "Akshaya A",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Akshaya_A_22d203.png",
  },
  {
    name: "Ramapriya",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/DSC_0029.png",
  },
  {
    name: "Amirtha Varshini",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/AmirthaVarshini.png",
  },
  {
    name: "Fathima Nashiba",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Fathima_Nashiba_22d214.png",
  },
  {
    name: "Harani C",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Harani_C_22h207.png",
  },
  {
    name: "Harini",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Harini_22h208.png",
  },
  {
    name: "Joshika",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Joshika_22R217.png",
  },
  {
    name: "Amirdavarshini K C",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/K.C._Amirdavarshini_22s019.png",
  },
  {
    name: "Lindsey R Macedo",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Lindsey.png",
  },
  {
    name: "Kishore",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Kishore.png",
  },
  {
    name: "Krishna Priya",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Krishna_Priya_22s050.png",
  },
  {
    name: "Sangamithra M S",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/M_S_Sangamithra_22i259.png",
  },
  {
    name: "Malavika",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Malavika_22s021.png",
  },
  {
    name: "Mohana Priya V M",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Mohana_Priya_V_M_22d230.png",
  },
  {
    name: "Nandini Priya",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Nandini_Priya_22l239.png",
  },
  {
    name: "Priyadharshini_22s029",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Priyadharshini_22s029.png",
  },
  {
    name: "Shabari Sri R",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/R_Shabari_Sri_22i253.png",
  },
  {
    name: "Ramya S",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/S_Ramya_22m147.png",
  },
  {
    name: "Sai Pravin",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Sai_Pravin.png",
  },
  {
    name: "Sakthi",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Sakthi_22N245.png",
  },
  {
    name: "Sowandara T",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Sowandara_T_22R246.png",
  },
  {
    name: "Swetha",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Swetha_21X049.png",
  },
  {
    name: "Thenmathi",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Thenmathi_22Y128.png",
  },
  {
    name: "Thnmozhi",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Thnmozhi_22y129.png",
  },
  {
    name: "Umavarshini",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Umavarshini_21x050.png",
  },
  {
    name: "Vijaya Varshini",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/Vijaya_Varshini_22N265.png",
  },
  {
    name: "Jeyam Palaniappan D",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/1jeyam.png",
  },
  {
    name: "T G Ashwin Kumar",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/2tg.png",
  },
  {
    name: "Rhubanraj P",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/3rhuban.jpg",
  },
  {
    name: "Sachitha C",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/4sachitha.png",
  },
  {
    name: "Sashti Amar R A",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/5sashti.png",
  },
  {
    name: "Ashwin V",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/6ashwin.png",
  },
  {
    name: "Pushparaj A",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/7pushparaj.png",
  },
  {
    name: "Balapravena A S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Balapravena_22b2.png",
  },
  {
    name: "Ajaykumar S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Ajaykumar_S_22b202.png",
  },
  {
    name: "Amirthavalli V",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Amirthavalli_V_22x007.png",
  },
  {
    name: "Aniruth",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aniruth_22A205.png",
  },
  {
    name: "Aswin Balamuragan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aswin.png",
  },
  {
    name: "Likkeeth Kumar.S.B",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Likkeeth.png",
  },
  {
    name: "Prethvish Mo",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Prethvish.png",
  },
  {
    name: "Praveen Venkit P",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Praveen_Venkit.png",
  },
  {
    name: "Jeevan G K",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Jeevan.png",
  },
  {
    name: "Akash S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aakash.png",
  },
  {
    name: "Aakash M",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aakash_20M601.png",
  },
  {
    name: "Kavya V.I",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Kavya_DESIGN.png",
  },
  {
    name: "Pradeep",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Pradeep.png",
  },
  {
    name: "Kavinkumar S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Kavin_21Y114.png",
  },
  {
    name: "Chandrakanth",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Chandrakanth_22N212.png",
  },
  {
    name: "Devanandh",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Devanandh_Y_22m607.png",
  },
  {
    name: "Eniyan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Eniyan_21s004.png",
  },
  {
    name: "Fasila Begum A",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Fasila_Begum_A_22d213.png",
  },
  {
    name: "Nandakishor G R",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/G.R.Nandakishor_22b211.png",
  },
  {
    name: "Giri Prassath S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Giri_Prassath_S_22z323.png",
  },
  {
    name: "Gokul",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Gokul.png",
  },
  {
    name: "Harisree",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Harisree.png",
  },
  {
    name: "Harrdik Krishna",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Harrdik_Krishna_22L163.png",
  },
  {
    name: "Harsha  Vardhana Ram A",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Harsha_Vardhana_Ram_A_22N220.png",
  },
  {
    name: "Jacin Wesly K",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Jacin_wesly_K_21E404.png",
  },
  {
    name: "Manoj Varun",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Manoj_varun.png",
  },
  {
    name: "Mugundan K",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Mugundan_K_22i236.png",
  },
  {
    name: "Naren Siddharth",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Naren_Siddharth_22z345.png",
  },
  {
    name: "Ohm Pranav",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Ohm_Pranav_22A230.png",
  },
  {
    name: "Pavithra",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Pavithra_22b230.png",
  },
  {
    name: "Purusoth Manak S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Purusoth_manak_S_22L134.png",
  },
  {
    name: "Ramkumar",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Ramkumar_22m621.png",
  },
  {
    name: "Sandhiya",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Sandhiya_22z258.png",
  },
  {
    name: "Sasi Garan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/SasiGaran.png",
  },
  {
    name: "Thaarugeshwari KS",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Thaarugeshwari_KS_22i270.png",
  },
  {
    name: "Thiyagarajan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Thiyagarajan.png",
  },
  {
    name: "Vijeyasri T",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Vijeyasri_T_22z272.png",
  },
  {
    name: "Vinaya Sri",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Vinaya_Sri_21b241.png",
  },
  {
    name: "Harivardhan S V",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/19M620.jpg",
  },
  {
    name: "Arulkumara B R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Arulkumara_B_R_22Z310.png",
  },
  {
    name: "Ashok Kumar",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Ashok_Kumar_22Y104.png",
  },
  {
    name: "Ashwin Ravichandran",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Ashwin_Ravichandran_21p602.png",
  },
  {
    name: "Sevathal S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Sevathal.png",
  },
  {
    name: "Ellakiyaa A",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Elakkiya_ERM.png",
  },
  {
    name: "Lalith Kumar B V",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/B.V.Lalith_Kumar_22i210.png",
  },
  {
    name: "Catherine Mary J",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Catherine_Mary_J_22N211.png",
  },
  {
    name: "Theetchana",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/DSC_0012.png",
  },
  {
    name: "Gokul B",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Gokul_B_22c107.png",
  },
  {
    name: "Gowthaman",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Gowthaman.png",
  },
  {
    name: "Harini M",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Harini_M_22N219.png",
  },
  {
    name: "Harini R C",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Harini_RC_22u217.png",
  },
  {
    name: "Kavya Subramani",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Kavya_Subramani_22z334.png",
  },
  {
    name: "Lakshman Raghav",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Lakshman_Raghav_.21p618JPG.png",
  },
  {
    name: "Nina Charles J",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Nina_Charles.png",
  },
  {
    name: "Akshaya K",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Akshaya.png",
  },
  {
    name: "Arunaa S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Aruna.png",
  },
  {
    name: "Selvakumar T",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Selvakumar.png",
  },
  {
    name: "Mullainathan V H",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Mullainathan.png",
  },
  {
    name: "Lokesh",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Lokesh.png",
  },
  {
    name: "Mithun",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Mithun.png",
  },
  {
    name: "Shuki",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Shuki_21x042.png",
  },
  {
    name: "Nandikka R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Nandikka_R_22i236.png",
  },
  {
    name: "NaveenKumar",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/NaveenKumar_2_e619.png",
  },
  {
    name: "Nitharsana",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Nitharsana_21b228.png",
  },
  {
    name: "Nivetha",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Nivetha.png",
  },
  {
    name: "Rhakshitha S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Rhakshitha_S_22i245.png",
  },
  {
    name: "Swathi S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/S_Swathi_21x048.png",
  },
  {
  
    name: "Sarumathi",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Sarumathi_22t125.png",
  },
  {
    name: "Simritha",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Simritha_22z364.png",
  },
  {
    name: "Sudharsan",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/Sudharsan_22Y217.png",
  },
  {
    name: "Mahimaa U",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/U_Mahimaa_22z371.png",
  },
  {
    name: "Dharmendra R",
    vertical: "Overall Coordinators",
    position: "Chairperson, Students Union",
    image_url: "/assets/Team/OBs/1dharmendra.jpeg",
  },
  {
    name: "Mano M",
    vertical: "Overall Coordinators",
    position: "Co-Chairperson, Students Union",
    image_url: "/assets/Team/OBs/2mano.jpeg",
  },
  {
    name: "Aditya Varma",
    vertical: "Overall Coordinators",
    position: "Secretary (Men), Students Union",
    image_url: "/assets/Team/OBs/3aditya.jpeg",
  },
  {
    name: "Sri Athrukshna B",
    vertical: "Overall Coordinators",
    position: "Secretary (Women), Students Union",
    image_url: "/assets/Team/OBs/4athrukshna.jpeg",
  },
  {
    name: "Pavana S",
    vertical: "Overall Coordinators",
    position: "Secretary (Science), Students Union",
    image_url: "/assets/Team/OBs/5pavana.jpeg",
  },
  {
    name: "Akshaiya",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Akshaiya_PR.png",
  },
  {
    name: "Raghan Harkesh R",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Raghan_Harkesh.png",
  },
  {
    name: "Deepti",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Deepti.png",
  },
  {
    name: "Manisha C",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Manisha_C_22d229.png",
  },
  {
    name: "Arunraja C",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Arun_Raja.png",
  },
  {
    name: "Lisalini.G",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Lisalini_21d218.png",
  },
  {
    name: "Sangamithra S",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Sangamithra.png",
  },
  {
    name: "Madumitha M P",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Madumitha_21c114.png",
  },
  {
    name: "Nakulan A",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Nakulan.png",
  },
  {
    name: "Reddy Jayakrishna",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Jayakrishana_Reddy.png",
  },
  {
    name: "Sreenitti S",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Srinithi.png",
  },
  {
    name: "Pramodini",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Pramodini_22z244.png",
  },
  {
    name: "Pranesh",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Pranesh_22m138.png",
  },
  {
    name: "Sakthi",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Sakthi_PR.png",
  },
  {
    name: "Sharmili",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Sharmili_G_22b240.png",
  },
  {
    name: "Swasthika",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Swasthika_PR.png",
  },
];

export default TeamDetails;
